### ISSUE TITLE
ignoreCustomPatterns execution requires ignoreCommonPatterns == false

### ISSUE THREAD

**Issue by julrichkieffer** [bevry/ignorefs#3]
There's a logic error in index.js: for the opts.ignoreCustomPatterns to be assessed, opts.ignoreCommonPatterns **must be** false.

This has several unintended affects:
 - opts.ignoreCustomPatterns can't evaluate while also ignoring typical dev files (a regression)
 - this highlights a lack of suitable test scenarios
 - Docpad no longer behaves as documented since replacing it's code with a dependency on this package (a regression)
 - the API (opts object) implies that none, some, all "filters" will apply if set and tested against a given path. This issue assumes this as the intended behaviour. If not, the API is insufficiently documented

**Comment by balupton** [comment]
for those interested, the problem is due to returning the result of the ignore, rather than just returning if the ignore was true - returning the result causes future checks to not be performed

https://github.com/bevry/ignorefs/blob/792d46df1b622c209397d914162480e3d47b3537/source/index.ts
